# Generated by Django 2.2.1 on 2019-05-30 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('user_type', models.IntegerField()),
                ('user_employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Employee')),
            ],
        ),
    ]
