# Generated by Django 2.2.1 on 2019-05-30 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_employee_id',
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapi.Employee'),
        ),
    ]
