# Generated by Django 2.2.1 on 2019-05-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0003_auto_20190530_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeID',
            field=models.CharField(max_length=50),
        ),
    ]
