# Generated by Django 2.2.1 on 2019-05-30 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0004_auto_20190530_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('speaker', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeID',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Employee'),
        ),
    ]
