# Generated by Django 2.2.1 on 2019-05-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0006_individualpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualpoints',
            name='actual_hours',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='individualpoints',
            name='hours_duration',
            field=models.TimeField(),
        ),
    ]
