# Generated by Django 2.2.1 on 2019-05-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0009_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolesResponsibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=255)),
                ('responsibilities', models.CharField(max_length=255)),
            ],
        ),
    ]
