# Generated by Django 2.2.1 on 2019-05-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0010_rolesresponsibilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TimeField()),
                ('breakout', models.TimeField()),
                ('breakin', models.TimeField()),
                ('logout', models.TimeField()),
            ],
        ),
    ]
