# Generated by Django 2.2.1 on 2019-05-30 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0011_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolesresponsibilities',
            old_name='roles',
            new_name='position',
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_employment', models.DateField()),
                ('date_effective', models.DateField()),
                ('quota', models.DecimalField(decimal_places=2, max_digits=16)),
                ('salary_base', models.DecimalField(decimal_places=2, max_digits=16)),
                ('basic_rate', models.DecimalField(decimal_places=2, max_digits=16)),
                ('incentive', models.DecimalField(decimal_places=2, max_digits=16)),
                ('challenge_quota', models.DecimalField(decimal_places=2, max_digits=16)),
                ('designation', models.CharField(max_length=255)),
                ('assignment', models.CharField(max_length=255)),
                ('employee_type', models.IntegerField()),
                ('employment_status', models.IntegerField()),
                ('resgination_date', models.DateField()),
                ('end_of_contract', models.DateField()),
                ('remarks_for_resignation_termination', models.CharField(max_length=255)),
                ('flexi', models.CharField(max_length=255)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Department')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Employee')),
                ('roles_responsibilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.RolesResponsibilities')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Schedule')),
            ],
        ),
    ]
