# Generated by Django 2.2.1 on 2019-05-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0012_auto_20190530_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmentdetails',
            old_name='resgination_date',
            new_name='resignation_date',
        ),
    ]
