# Generated by Django 2.2.1 on 2019-06-05 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0016_auto_20190605_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Employee')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Training')),
            ],
        ),
    ]
