# Generated by Django 2.2.1 on 2019-06-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0018_auto_20190607_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_duration',
            field=models.IntegerField(),
        ),
    ]
