# Generated by Django 2.2.1 on 2019-06-11 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('birthday', models.DateField()),
                ('citizenship', models.CharField(max_length=20)),
                ('height', models.DecimalField(decimal_places=2, max_digits=16)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=16)),
                ('blood_type', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RolesResponsibilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, unique=True)),
                ('responsibilities', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TimeField()),
                ('breakout', models.TimeField()),
                ('breakin', models.TimeField()),
                ('logout', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('speaker', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('training_duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('user_type', models.IntegerField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Trainees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Employee')),
                ('training_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Training')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('points', models.IntegerField()),
                ('hours_classification', models.CharField(max_length=50)),
                ('hours_duration', models.TimeField()),
                ('actual_hours', models.TimeField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_employment', models.DateField()),
                ('date_effective', models.DateField()),
                ('quota', models.DecimalField(decimal_places=2, max_digits=16)),
                ('salary_base', models.DecimalField(decimal_places=2, max_digits=16)),
                ('basic_rate', models.DecimalField(decimal_places=2, max_digits=16)),
                ('incentive', models.DecimalField(decimal_places=2, max_digits=16)),
                ('challenge_quota', models.DecimalField(decimal_places=2, max_digits=16)),
                ('designation', models.CharField(max_length=255)),
                ('assignment', models.CharField(max_length=255)),
                ('employee_type', models.IntegerField()),
                ('employment_status', models.IntegerField()),
                ('resignation_date', models.DateField()),
                ('end_of_contract', models.DateField()),
                ('remarks_for_resignation_termination', models.CharField(max_length=255)),
                ('flexi', models.IntegerField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Department')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Employee')),
                ('roles_responsibilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.RolesResponsibilities')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=50)),
                ('certified_by', models.CharField(max_length=50)),
                ('performance_rating', models.DecimalField(decimal_places=2, max_digits=16)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.CharField(max_length=255)),
                ('training_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Training')),
            ],
        ),
    ]
