# Generated by Django 2.2.1 on 2019-06-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
