# Generated by Django 2.2.1 on 2019-06-20 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0003_employee_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmentdetails',
            old_name='date_employment',
            new_name='date_employed',
        ),
    ]
