# Generated by Django 2.2.1 on 2019-07-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0005_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
