# Generated by Django 2.2.1 on 2019-07-11 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0006_auto_20190711_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='timeDisplay',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
