# Generated by Django 2.2.1 on 2019-07-11 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0007_training_timedisplay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='training_duration',
        ),
        migrations.AddField(
            model_name='training',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
