# Generated by Django 2.2.1 on 2019-07-12 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0011_auto_20190712_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employeeprofile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='individualpoints',
        ),
        migrations.RemoveField(
            model_name='user',
            name='training',
        ),
    ]
