# Generated by Django 2.2.1 on 2019-07-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0012_auto_20190712_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='name',
            new_name='training_name',
        ),
    ]
