# Generated by Django 2.2.1 on 2019-07-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0013_auto_20190713_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='training_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='budget',
            name='training_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_name', to='adminapi.Training'),
        ),
    ]
