# Generated by Django 2.2.1 on 2019-07-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0014_auto_20190713_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='training_name',
            new_name='training',
        ),
    ]
