# Generated by Django 2.2.1 on 2019-07-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0016_auto_20190713_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='name',
            new_name='training',
        ),
    ]
