# Generated by Django 2.2.1 on 2019-07-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0017_auto_20190713_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training',
            field=models.CharField(max_length=50),
        ),
    ]
