# Generated by Django 2.2.1 on 2019-07-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0020_auto_20190713_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainees',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
