# Generated by Django 2.2.1 on 2019-07-14 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0021_auto_20190713_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employmentdetails',
            old_name='roles_responsibilities',
            new_name='roles_responsibilities_id',
        ),
    ]
