# Generated by Django 2.2.1 on 2019-07-14 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0022_auto_20190714_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualpoints',
            old_name='hours_classification',
            new_name='admin',
        ),
        migrations.RemoveField(
            model_name='individualpoints',
            name='actual_hours',
        ),
        migrations.RemoveField(
            model_name='individualpoints',
            name='hours_duration',
        ),
        migrations.AddField(
            model_name='individualpoints',
            name='extra_wordload',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualpoints',
            name='investment',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualpoints',
            name='management',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualpoints',
            name='non_billiable',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualpoints',
            name='nonpaid_billiable',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualpoints',
            name='paid',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualpoints',
            name='sales',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualpoints',
            name='training',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualpoints',
            name='points',
            field=models.CharField(max_length=50),
        ),
    ]
