# Generated by Django 2.2.1 on 2019-07-14 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0023_auto_20190714_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualpoints',
            name='admin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='individualpoints',
            name='extra_wordload',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='individualpoints',
            name='investment',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='individualpoints',
            name='management',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='individualpoints',
            name='non_billiable',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='individualpoints',
            name='nonpaid_billiable',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='individualpoints',
            name='paid',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='individualpoints',
            name='points',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='individualpoints',
            name='sales',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='individualpoints',
            name='training',
            field=models.TimeField(),
        ),
    ]
