# Generated by Django 2.2.1 on 2019-07-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0025_auto_20190714_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualpoints',
            name='points',
            field=models.CharField(max_length=50),
        ),
    ]
