# Generated by Django 2.2.1 on 2019-07-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0028_auto_20190714_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentdetails',
            name='end_of_contract',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employmentdetails',
            name='resignation_date',
            field=models.DateField(blank=True),
        ),
    ]
