# Generated by Django 2.2.1 on 2019-07-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0029_auto_20190723_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentdetails',
            name='end_of_contract',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employmentdetails',
            name='resignation_date',
            field=models.DateField(),
        ),
    ]
