# Generated by Django 2.2.1 on 2019-07-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0030_auto_20190723_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='profilepic'),
        ),
    ]
