# Generated by Django 2.2.3 on 2019-07-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0033_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='quota',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
    ]
