# Generated by Django 2.2.3 on 2019-08-05 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0034_auto_20190729_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_employed', models.CharField(max_length=255)),
                ('date_effective', models.CharField(max_length=255)),
                ('quota', models.CharField(max_length=255)),
                ('salary_base', models.CharField(max_length=255)),
                ('basic_rate', models.CharField(max_length=255)),
                ('incentive', models.CharField(max_length=255)),
                ('challenge_quota', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('assignment', models.CharField(max_length=255)),
                ('employee_type', models.CharField(max_length=255)),
                ('employment_status', models.CharField(max_length=255)),
                ('resignation_date', models.CharField(max_length=255)),
                ('end_of_contract', models.CharField(max_length=255)),
                ('remarks_for_resignation_termination', models.CharField(max_length=255)),
                ('flexi', models.CharField(max_length=255)),
                ('date_updated', models.CharField(max_length=255)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Department')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Employee')),
                ('roles_responsibilities_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.RolesResponsibilities')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Schedule')),
            ],
        ),
        migrations.DeleteModel(
            name='Quota',
        ),
    ]
