# Generated by Django 2.2.3 on 2019-08-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0036_auto_20190805_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='date_updated',
            field=models.DateField(),
        ),
    ]
