# Generated by Django 2.2.3 on 2019-08-05 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0038_employmenthistory_schedule_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='schedule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapi.Schedule'),
        ),
    ]
