# Generated by Django 2.2.3 on 2019-08-05 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0041_auto_20190805_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentdetails',
            name='end_of_contract',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employmentdetails',
            name='resignation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
