# Generated by Django 2.2.3 on 2019-08-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0043_userlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogs',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userlogs',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
