# Generated by Django 2.2.3 on 2019-08-07 22:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0044_auto_20190807_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogs',
            name='user_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
