# Generated by Django 2.2.3 on 2019-08-08 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0045_userlogs_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogs',
            name='user_type',
        ),
    ]
