# Generated by Django 2.2.3 on 2019-08-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0046_remove_userlogs_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeParentBox', models.CharField(max_length=255)),
                ('employeeList', models.CharField(max_length=255)),
                ('employeeForm', models.CharField(max_length=255)),
                ('employmentInfo', models.CharField(max_length=255)),
                ('employmentHistory', models.CharField(max_length=255)),
                ('trainingEmployee', models.CharField(max_length=255)),
                ('evaluation', models.CharField(max_length=255)),
                ('individualPoints', models.CharField(max_length=255)),
                ('trainingSeminar', models.CharField(max_length=255)),
                ('trainingList', models.CharField(max_length=255)),
                ('trainingForm', models.CharField(max_length=255)),
                ('reports', models.CharField(max_length=255)),
                ('adminSettings', models.CharField(max_length=255)),
                ('departmentSettings', models.CharField(max_length=255)),
                ('userSettings', models.CharField(max_length=255)),
                ('userLogs', models.CharField(max_length=255)),
            ],
        ),
    ]
