# Generated by Django 2.2.3 on 2019-08-12 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0048_accountsettings_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsettings',
            old_name='employeeParentBox',
            new_name='employeeProfile',
        ),
    ]
