# Generated by Django 2.2.3 on 2019-08-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0049_auto_20190812_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='user_type',
            field=models.BooleanField(),
        ),
    ]
