# Generated by Django 2.2.3 on 2019-08-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0050_auto_20190812_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='adminSettings',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='departmentSettings',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='employeeForm',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='employeeList',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='employeeProfile',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='employmentHistory',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='employmentInfo',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='evaluation',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='individualPoints',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='reports',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='trainingEmployee',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='trainingForm',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='trainingList',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='trainingSeminar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='userLogs',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='userSettings',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='user_type',
            field=models.CharField(max_length=255),
        ),
    ]
