# Generated by Django 2.2.3 on 2019-08-13 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0051_auto_20190812_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsettings',
            name='trainingForm',
        ),
        migrations.RemoveField(
            model_name='accountsettings',
            name='trainingList',
        ),
    ]
