# Generated by Django 2.2.3 on 2019-08-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0052_auto_20190813_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='remarks_for_resignation_termination',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
