# Generated by Django 2.2.3 on 2019-08-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0053_auto_20190813_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='remarks_for_resignation_termination',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
