# Generated by Django 2.2.3 on 2019-08-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0055_auto_20190813_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_of_contract',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='resignation_date',
            field=models.DateField(null=True),
        ),
    ]
