# Generated by Django 2.2.3 on 2019-08-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0058_auto_20190813_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentdetails',
            name='challenge_quota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='challenge_quota',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='quota',
            field=models.CharField(max_length=255),
        ),
    ]
