# Generated by Django 2.2.3 on 2019-08-19 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0059_auto_20190813_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsettings',
            name='positionResponsibilities',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
